# Generated by Django 3.1.1 on 2020-11-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
