# Generated by Django 3.1.1 on 2020-11-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_quest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='image_directory',
            field=models.TextField(default="{% static 'img/q.jpg' %}"),
        ),
    ]
