# Generated by Django 3.1.1 on 2020-11-26 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quest', '0002_quest_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anstext', models.CharField(max_length=255, verbose_name='Вариант ответа')),
                ('is_true', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quest.question')),
            ],
        ),
        migrations.AlterField(
            model_name='quest',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Квест активен'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название квеста'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_true', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость вопроса')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quest.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
