# Generated by Django 3.1.1 on 2020-11-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_quest_image_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='image_directory',
            field=models.CharField(default="{% static 'img/q.jpg' %}", max_length=255),
        ),
    ]
