# Generated by Django 3.1.1 on 2020-11-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_auto_20201126_1300'),
        ('quest', '0003_auto_20201126_1407'),
    ]

    operations = [
    ]
