# Generated by Django 3.1.1 on 2020-11-26 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quest', '0005_merge_20201126_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='point',
            field=models.TextField(default='55.753600, 37.621094'),
        ),
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.TextField(default='55.753600, 37.621094'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='image_directory',
            field=models.CharField(default='img/q.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='quest',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Викторина активна'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
